name: Docker Image CI

on:
  push:
    branches:
      - 'master'

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Cleanup
        run: |
          sudo apt-get remove -y '^ghc-8.*'
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^llvm-.*'
          sudo apt-get remove -y 'php.*'
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo rm -rf "/opt/*"
          sudo rm -rf "/usr/local"
          sudo rm -rf "/usr/share/dotnet/"
          docker image prune -a -f
          docker volume prune -f
          df -h
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/mips64le
          push: true
          tags: vxst/workspace:latest
