name: Docker Image CI

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '30 19 * * 5'

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Cleanup
        run: |
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo rm -rf "/opt/*"
          sudo rm -rf "/usr/local"
          sudo rm -rf "/usr/share/dotnet/"
          docker image prune -a -f
          docker volume prune -f
          df -h
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          cache-from: type=registry,ref=vxst/workspace:latest
          cache-to: type=inline
          push: true
          tags: vxst/workspace:latest, vxst/workspace:${{ steps.date.outputs.date }}
